export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/icons8-hamburger-96.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/icons8-hamburger-96.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/images/icons8-hamburger-96.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/images/icons8-hamburger-96.png"),
  },
  {
    id: 5,
    name: "Sweets",
    image: require("../assets/images/icons8-hamburger-96.png"),
  },
  {
    id: 6,
    name: "Noodles",
    image: require("../assets/images/icons8-hamburger-96.png"),
  },
];

export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Papa Johns",
      image: require("../assets/images/chicken.jpeg"),
      description: "Hot and spicy chicken",
      lng: 38.22134234,
      lat: -86.32432234,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
        {
          id: 2,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
        {
          id: 3,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
        {
          id: 4,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
      ],
    },
    {
      id: 2,
      name: "Papa Johns",
      image: require("../assets/images/chicken.jpeg"),
      description: "Hot and spicy chicken",
      lng: 38.22134234,
      lat: -86.32432234,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
        {
          id: 2,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
        {
          id: 3,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
        {
          id: 4,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
      ],
    },
    {
      id: 3,
      name: "Papa Johns",
      image: require("../assets/images/chicken.jpeg"),
      description: "Hot and spicy chicken",
      lng: 38.22134234,
      lat: -86.32432234,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
        {
          id: 2,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
        {
          id: 3,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
        {
          id: 4,
          name: "chicken",
          description: "cheezy garlic chicken",
          price: 10,
          image: require("../assets/images/rice.jpeg"),
        },
      ],
    },
  ],
};
